/**
 * ZamanAI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Chat request
 */
export interface ChatRequest { 
    conversation_id: string;
    user_id: string;
    user_name: string;
    user_message: string;
}

