/**
 * ZamanAI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GoalConfig } from './goal-config';
import { Intent } from './intent';


/**
 * Chat response
 */
export interface ChatResponse { 
    conversation_id: string;
    user_id: string;
    assistant_message: string;
    intent: Intent;
    goal_config: GoalConfig;
}
export namespace ChatResponse {
}


