/**
 * ZamanAI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageSchema } from './message-schema';


/**
 * Response containing conversation message history
 */
export interface ConversationHistoryResponse { 
    conversation_id: string;
    messages: Array<MessageSchema>;
}

