/**
 * ZamanAI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Conversation detail
 */
export interface ConversationDetail { 
    conversation_id: string;
    user_id: string;
    conversation_name: string;
    created_at: string;
    updated_at: string;
}

