/**
 * ZamanAI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to create a new conversation
 */
export interface CreateConversationRequest { 
    user_id: string;
    conversation_name: string;
}

