/**
 * ZamanAI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Goal config - all monetary amounts in KZT (Tenge)
 */
export interface GoalConfig { 
    is_ready: boolean;
    goal_name: string;
    monthly_investment: number;
    current_balance: number;
    target_sum: number;
}

