/**
 * ZamanAI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Intent classification
 */
export const Intent = {
    Chat: 'chat',
    Goal: 'goal'
} as const;
export type Intent = typeof Intent[keyof typeof Intent];

