/**
 * ZamanAI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Individual message in conversation history
 */
export interface MessageSchema { 
    role: string;
    content: string;
}

