/**
 * ZamanAI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response from transcription endpoint
 */
export interface TranscriptionResponse { 
    /**
     * The raw transcribed text from the audio
     */
    original_text: string;
    /**
     * The enhanced/cleaned version of the transcription ready for further processing
     */
    enhanced_text: string;
    /**
     * Detected language of the audio (e.g., \'en\', \'kk\', \'ru\')
     */
    language: string;
}

