/**
 * FNU API (development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoalModel { 
    id: string;
    createDate?: string;
    userId: string;
    name: string;
    durationMonth: number;
    monthlyInvest: number;
    target: number;
    estimatedDate: string;
    balance: number;
    completed: boolean;
}

