ext {
	commonsIo = "commons-io:commons-io:2.16.1"
	commonsCollections = "org.apache.commons:commons-collections4:4.4"
	commonsCodec = "commons-codec:commons-codec:1.17.0"
	commonsLang = "org.apache.commons:commons-lang3:3.14.0"
	commonsMath = "org.apache.commons:commons-math3:3.6.1"
	postgresDriver = "org.postgresql:postgresql:42.7.3"

    jooq = "org.jooq:jooq:${jooqVersion}"
    jooqMeta = "org.jooq:jooq-meta:${jooqVersion}"
    jooqCodegen = "org.jooq:jooq-codegen:${jooqVersion}"
    db = [postgresDriver]
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'idea'
    apply plugin: 'maven-publish'

    group = 'com.hnu'

    dependencies {
        api enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")

		// https://mvnrepository.com/artifact/jakarta.validation/jakarta.validation-api
//		api 'jakarta.validation:jakarta.validation-api:3.1.1'

		api 'io.quarkus:quarkus-rest-client'
		api 'io.quarkus:quarkus-rest-client-jackson'
		api 'io.quarkus:quarkus-arc'
		api 'io.quarkus:quarkus-hibernate-validator'
		api 'io.quarkus:quarkus-vertx'
		api 'io.quarkus.qute:qute-core'

		api 'org.jboss.logmanager:log4j2-jboss-logmanager'
	}

	configurations.configureEach {
		exclude group: 'org.slf4j', module: 'slf4j-log4j12'
		exclude group: 'org.slf4j', module: 'slf4j-jdk14'
		exclude group: 'log4j', module: 'log4j'
	}

    compileJava {
        options.generatedSourceOutputDirectory.set(new File(projectDir, "/src/main/generated"))
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.register('cleanGen', Delete) {
        delete "${projectDir}/src/main/generated"
    }

    tasks.clean.dependsOn(tasks.cleanGen)

    idea {
        module {
            generatedSourceDirs += new File(projectDir, "src/main/generated")
            outputDir file('build/classes/java/main')
            testOutputDir file('build/classes/java/test')
        }
    }

    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }

    repositories {
        mavenCentral()
        maven {
            url "https://packages.confluent.io/maven/"
        }
        mavenLocal()
    }
}

tasks.register('schemaSnapshot', Exec) {
    commandLine 'sh', 'scripts/db-dump.sh'
}

schemaSnapshot.dependsOn ':dao:jooq-generator:run'

tasks.register('dbMigrate') {
    dependsOn 'dao:nu:flywayMigrate'
    dependsOn 'schemaSnapshot'
    tasks.findByName('schemaSnapshot').mustRunAfter 'dao:nu:flywayMigrate'
}

