/*
 * This file is generated by jOOQ.
 */
package com.hnu.db.jooq.model.tables.records;


import com.hnu.db.jooq.model.tables.NuGoals;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NuGoalRecord extends UpdatableRecordImpl<NuGoalRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.nu_goals.id_</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.nu_goals.id_</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.nu_goals.removed_</code>.
     */
    public void setRemoved(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.nu_goals.removed_</code>.
     */
    public Boolean getRemoved() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.nu_goals.create_date_</code>.
     */
    public void setCreateDate(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.nu_goals.create_date_</code>.
     */
    public OffsetDateTime getCreateDate() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.nu_goals.modify_date_</code>.
     */
    public void setModifyDate(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.nu_goals.modify_date_</code>.
     */
    public OffsetDateTime getModifyDate() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.nu_goals.user_id_</code>.
     */
    public void setUserId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.nu_goals.user_id_</code>.
     */
    public UUID getUserId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.nu_goals.name_</code>.
     */
    public void setName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.nu_goals.name_</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.nu_goals.duration_month_</code>.
     */
    public void setDurationMonth(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.nu_goals.duration_month_</code>.
     */
    public Integer getDurationMonth() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.nu_goals.monthly_invest_</code>.
     */
    public void setMonthlyInvest(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.nu_goals.monthly_invest_</code>.
     */
    public BigDecimal getMonthlyInvest() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>public.nu_goals.target_</code>.
     */
    public void setTarget(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.nu_goals.target_</code>.
     */
    public BigDecimal getTarget() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>public.nu_goals.estimated_date_</code>.
     */
    public void setEstimatedDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.nu_goals.estimated_date_</code>.
     */
    public LocalDateTime getEstimatedDate() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.nu_goals.balance_</code>.
     */
    public void setBalance(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.nu_goals.balance_</code>.
     */
    public BigDecimal getBalance() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>public.nu_goals.completed_</code>.
     */
    public void setCompleted(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.nu_goals.completed_</code>.
     */
    public Boolean getCompleted() {
        return (Boolean) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NuGoalRecord
     */
    public NuGoalRecord() {
        super(NuGoals.NU_GOALS);
    }

    /**
     * Create a detached, initialised NuGoalRecord
     */
    public NuGoalRecord(UUID id_, Boolean removed_, OffsetDateTime createDate_, OffsetDateTime modifyDate_, UUID userId_, String name_, Integer durationMonth_, BigDecimal monthlyInvest_, BigDecimal target_, LocalDateTime estimatedDate_, BigDecimal balance_, Boolean completed_) {
        super(NuGoals.NU_GOALS);

        setId(id_);
        setRemoved(removed_);
        setCreateDate(createDate_);
        setModifyDate(modifyDate_);
        setUserId(userId_);
        setName(name_);
        setDurationMonth(durationMonth_);
        setMonthlyInvest(monthlyInvest_);
        setTarget(target_);
        setEstimatedDate(estimatedDate_);
        setBalance(balance_);
        setCompleted(completed_);
        resetTouchedOnNotNull();
    }
}
