/*
 * This file is generated by jOOQ.
 */
package com.hnu.db.jooq.model.tables.records;


import com.hnu.db.jooq.model.tables.NuGoalTransactions;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NuGoalTransactionRecord extends UpdatableRecordImpl<NuGoalTransactionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.nu_goal_transactions.id_</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.nu_goal_transactions.id_</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.nu_goal_transactions.removed_</code>.
     */
    public void setRemoved(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.nu_goal_transactions.removed_</code>.
     */
    public Boolean getRemoved() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.nu_goal_transactions.create_date_</code>.
     */
    public void setCreateDate(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.nu_goal_transactions.create_date_</code>.
     */
    public OffsetDateTime getCreateDate() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.nu_goal_transactions.modify_date_</code>.
     */
    public void setModifyDate(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.nu_goal_transactions.modify_date_</code>.
     */
    public OffsetDateTime getModifyDate() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.nu_goal_transactions.goal_id_</code>.
     */
    public void setGoalId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.nu_goal_transactions.goal_id_</code>.
     */
    public UUID getGoalId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.nu_goal_transactions.amount_</code>.
     */
    public void setAmount(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.nu_goal_transactions.amount_</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.nu_goal_transactions.date_</code>.
     */
    public void setDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.nu_goal_transactions.date_</code>.
     */
    public LocalDateTime getDate() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NuGoalTransactionRecord
     */
    public NuGoalTransactionRecord() {
        super(NuGoalTransactions.NU_GOAL_TRANSACTIONS);
    }

    /**
     * Create a detached, initialised NuGoalTransactionRecord
     */
    public NuGoalTransactionRecord(UUID id_, Boolean removed_, OffsetDateTime createDate_, OffsetDateTime modifyDate_, UUID goalId_, BigDecimal amount_, LocalDateTime date_) {
        super(NuGoalTransactions.NU_GOAL_TRANSACTIONS);

        setId(id_);
        setRemoved(removed_);
        setCreateDate(createDate_);
        setModifyDate(modifyDate_);
        setGoalId(goalId_);
        setAmount(amount_);
        setDate(date_);
        resetTouchedOnNotNull();
    }
}
