/*
 * This file is generated by jOOQ.
 */
package com.hnu.db.jooq.model.tables.records;


import com.hnu.db.jooq.model.tables.NuOtpRequests;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NuOtpRequestRecord extends UpdatableRecordImpl<NuOtpRequestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.nu_otp_requests.id_</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.nu_otp_requests.id_</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.nu_otp_requests.removed_</code>.
     */
    public void setRemoved(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.nu_otp_requests.removed_</code>.
     */
    public Boolean getRemoved() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.nu_otp_requests.create_date_</code>.
     */
    public void setCreateDate(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.nu_otp_requests.create_date_</code>.
     */
    public OffsetDateTime getCreateDate() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.nu_otp_requests.modify_date_</code>.
     */
    public void setModifyDate(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.nu_otp_requests.modify_date_</code>.
     */
    public OffsetDateTime getModifyDate() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.nu_otp_requests.modify_user_id_</code>.
     */
    public void setModifyUserId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.nu_otp_requests.modify_user_id_</code>.
     */
    public UUID getModifyUserId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.nu_otp_requests.code_</code>.
     */
    public void setCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.nu_otp_requests.code_</code>.
     */
    public String getCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.nu_otp_requests.otp_id_</code>.
     */
    public void setOtpId(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.nu_otp_requests.otp_id_</code>.
     */
    public UUID getOtpId() {
        return (UUID) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NuOtpRequestRecord
     */
    public NuOtpRequestRecord() {
        super(NuOtpRequests.NU_OTP_REQUESTS);
    }

    /**
     * Create a detached, initialised NuOtpRequestRecord
     */
    public NuOtpRequestRecord(UUID id_, Boolean removed_, OffsetDateTime createDate_, OffsetDateTime modifyDate_, UUID modifyUserId_, String code_, UUID otpId_) {
        super(NuOtpRequests.NU_OTP_REQUESTS);

        setId(id_);
        setRemoved(removed_);
        setCreateDate(createDate_);
        setModifyDate(modifyDate_);
        setModifyUserId(modifyUserId_);
        setCode(code_);
        setOtpId(otpId_);
        resetTouchedOnNotNull();
    }
}
