/*
 * This file is generated by jOOQ.
 */
package com.hnu.db.jooq.model.tables.records;


import com.hnu.db.jooq.model.tables.NuOtps;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NuOtpRecord extends UpdatableRecordImpl<NuOtpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.nu_otps.id_</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.nu_otps.id_</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.nu_otps.removed_</code>.
     */
    public void setRemoved(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.nu_otps.removed_</code>.
     */
    public Boolean getRemoved() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.nu_otps.create_date_</code>.
     */
    public void setCreateDate(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.nu_otps.create_date_</code>.
     */
    public OffsetDateTime getCreateDate() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.nu_otps.modify_date_</code>.
     */
    public void setModifyDate(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.nu_otps.modify_date_</code>.
     */
    public OffsetDateTime getModifyDate() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.nu_otps.modify_user_id_</code>.
     */
    public void setModifyUserId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.nu_otps.modify_user_id_</code>.
     */
    public UUID getModifyUserId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.nu_otps.user_id_</code>.
     */
    public void setUserId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.nu_otps.user_id_</code>.
     */
    public UUID getUserId() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.nu_otps.code_</code>.
     */
    public void setCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.nu_otps.code_</code>.
     */
    public String getCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.nu_otps.success_date_</code>.
     */
    public void setSuccessDate(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.nu_otps.success_date_</code>.
     */
    public OffsetDateTime getSuccessDate() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.nu_otps.expire_date_</code>.
     */
    public void setExpireDate(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.nu_otps.expire_date_</code>.
     */
    public OffsetDateTime getExpireDate() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.nu_otps.phone_</code>.
     */
    public void setPhone(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.nu_otps.phone_</code>.
     */
    public String getPhone() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.nu_otps.session_id_</code>.
     */
    public void setSessionId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.nu_otps.session_id_</code>.
     */
    public String getSessionId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.nu_otps.authenticator_</code>.
     */
    public void setAuthenticator(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.nu_otps.authenticator_</code>.
     */
    public String getAuthenticator() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NuOtpRecord
     */
    public NuOtpRecord() {
        super(NuOtps.NU_OTPS);
    }

    /**
     * Create a detached, initialised NuOtpRecord
     */
    public NuOtpRecord(UUID id_, Boolean removed_, OffsetDateTime createDate_, OffsetDateTime modifyDate_, UUID modifyUserId_, UUID userId_, String code_, OffsetDateTime successDate_, OffsetDateTime expireDate_, String phone_, String sessionId_, String authenticator_) {
        super(NuOtps.NU_OTPS);

        setId(id_);
        setRemoved(removed_);
        setCreateDate(createDate_);
        setModifyDate(modifyDate_);
        setModifyUserId(modifyUserId_);
        setUserId(userId_);
        setCode(code_);
        setSuccessDate(successDate_);
        setExpireDate(expireDate_);
        setPhone(phone_);
        setSessionId(sessionId_);
        setAuthenticator(authenticator_);
        resetTouchedOnNotNull();
    }
}
