/*
 * This file is generated by jOOQ.
 */
package com.hnu.db.jooq.model.tables.records;


import com.hnu.db.jooq.model.tables.NuSessions;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NuSessionRecord extends TableRecordImpl<NuSessionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.nu_sessions.session_id_</code>.
     */
    public void setSessionId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.nu_sessions.session_id_</code>.
     */
    public String getSessionId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.nu_sessions.removed_</code>.
     */
    public void setRemoved(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.nu_sessions.removed_</code>.
     */
    public Boolean getRemoved() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.nu_sessions.create_date_</code>.
     */
    public void setCreateDate(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.nu_sessions.create_date_</code>.
     */
    public OffsetDateTime getCreateDate() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.nu_sessions.modify_date_</code>.
     */
    public void setModifyDate(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.nu_sessions.modify_date_</code>.
     */
    public OffsetDateTime getModifyDate() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.nu_sessions.user_id_</code>.
     */
    public void setUserId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.nu_sessions.user_id_</code>.
     */
    public UUID getUserId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.nu_sessions.phone_</code>.
     */
    public void setPhone(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.nu_sessions.phone_</code>.
     */
    public String getPhone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.nu_sessions.data_</code>.
     */
    public void setData(JSONB value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.nu_sessions.data_</code>.
     */
    public JSONB getData() {
        return (JSONB) get(6);
    }

    /**
     * Setter for <code>public.nu_sessions.expire_date_</code>.
     */
    public void setExpireDate(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.nu_sessions.expire_date_</code>.
     */
    public OffsetDateTime getExpireDate() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.nu_sessions.device_id_</code>.
     */
    public void setDeviceId(UUID value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.nu_sessions.device_id_</code>.
     */
    public UUID getDeviceId() {
        return (UUID) get(8);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NuSessionRecord
     */
    public NuSessionRecord() {
        super(NuSessions.NU_SESSIONS);
    }

    /**
     * Create a detached, initialised NuSessionRecord
     */
    public NuSessionRecord(String sessionId_, Boolean removed_, OffsetDateTime createDate_, OffsetDateTime modifyDate_, UUID userId_, String phone_, JSONB data_, OffsetDateTime expireDate_, UUID deviceId_) {
        super(NuSessions.NU_SESSIONS);

        setSessionId(sessionId_);
        setRemoved(removed_);
        setCreateDate(createDate_);
        setModifyDate(modifyDate_);
        setUserId(userId_);
        setPhone(phone_);
        setData(data_);
        setExpireDate(expireDate_);
        setDeviceId(deviceId_);
        resetTouchedOnNotNull();
    }
}
