/*
 * This file is generated by jOOQ.
 */
package com.hnu.db.jooq.model.tables.records;


import com.hnu.db.jooq.model.tables.NuTransactions;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NuTransactionRecord extends UpdatableRecordImpl<NuTransactionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.nu_transactions.id_</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.nu_transactions.id_</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.nu_transactions.removed_</code>.
     */
    public void setRemoved(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.nu_transactions.removed_</code>.
     */
    public Boolean getRemoved() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.nu_transactions.create_date_</code>.
     */
    public void setCreateDate(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.nu_transactions.create_date_</code>.
     */
    public OffsetDateTime getCreateDate() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.nu_transactions.modify_date_</code>.
     */
    public void setModifyDate(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.nu_transactions.modify_date_</code>.
     */
    public OffsetDateTime getModifyDate() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.nu_transactions.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.nu_transactions.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.nu_transactions.amount_</code>.
     */
    public void setAmount(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.nu_transactions.amount_</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.nu_transactions.category_type_</code>.
     */
    public void setCategoryType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.nu_transactions.category_type_</code>.
     */
    public String getCategoryType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.nu_transactions.date_</code>.
     */
    public void setDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.nu_transactions.date_</code>.
     */
    public LocalDateTime getDate() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NuTransactionRecord
     */
    public NuTransactionRecord() {
        super(NuTransactions.NU_TRANSACTIONS);
    }

    /**
     * Create a detached, initialised NuTransactionRecord
     */
    public NuTransactionRecord(UUID id_, Boolean removed_, OffsetDateTime createDate_, OffsetDateTime modifyDate_, UUID userId, BigDecimal amount_, String categoryType_, LocalDateTime date_) {
        super(NuTransactions.NU_TRANSACTIONS);

        setId(id_);
        setRemoved(removed_);
        setCreateDate(createDate_);
        setModifyDate(modifyDate_);
        setUserId(userId);
        setAmount(amount_);
        setCategoryType(categoryType_);
        setDate(date_);
        resetTouchedOnNotNull();
    }
}
