/*
 * This file is generated by jOOQ.
 */
package com.hnu.db.jooq.model.tables.records;


import com.hnu.db.jooq.model.tables.NuUsers;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NuUserRecord extends UpdatableRecordImpl<NuUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.nu_users.id_</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.nu_users.id_</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.nu_users.removed_</code>.
     */
    public void setRemoved(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.nu_users.removed_</code>.
     */
    public Boolean getRemoved() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.nu_users.create_date_</code>.
     */
    public void setCreateDate(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.nu_users.create_date_</code>.
     */
    public OffsetDateTime getCreateDate() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.nu_users.modify_date_</code>.
     */
    public void setModifyDate(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.nu_users.modify_date_</code>.
     */
    public OffsetDateTime getModifyDate() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.nu_users.modify_user_id_</code>.
     */
    public void setModifyUserId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.nu_users.modify_user_id_</code>.
     */
    public UUID getModifyUserId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.nu_users.enabled_</code>.
     */
    public void setEnabled(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.nu_users.enabled_</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.nu_users.phone_</code>.
     */
    public void setPhone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.nu_users.phone_</code>.
     */
    public String getPhone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.nu_users.firstname_</code>.
     */
    public void setFirstname(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.nu_users.firstname_</code>.
     */
    public String getFirstname() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.nu_users.lastname_</code>.
     */
    public void setLastname(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.nu_users.lastname_</code>.
     */
    public String getLastname() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.nu_users.patronymic_</code>.
     */
    public void setPatronymic(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.nu_users.patronymic_</code>.
     */
    public String getPatronymic() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.nu_users.iin_</code>.
     */
    public void setIin(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.nu_users.iin_</code>.
     */
    public String getIin() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.nu_users.birth_date_</code>.
     */
    public void setBirthDate(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.nu_users.birth_date_</code>.
     */
    public OffsetDateTime getBirthDate() {
        return (OffsetDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NuUserRecord
     */
    public NuUserRecord() {
        super(NuUsers.NU_USERS);
    }

    /**
     * Create a detached, initialised NuUserRecord
     */
    public NuUserRecord(UUID id_, Boolean removed_, OffsetDateTime createDate_, OffsetDateTime modifyDate_, UUID modifyUserId_, Boolean enabled_, String phone_, String firstname_, String lastname_, String patronymic_, String iin_, OffsetDateTime birthDate_) {
        super(NuUsers.NU_USERS);

        setId(id_);
        setRemoved(removed_);
        setCreateDate(createDate_);
        setModifyDate(modifyDate_);
        setModifyUserId(modifyUserId_);
        setEnabled(enabled_);
        setPhone(phone_);
        setFirstname(firstname_);
        setLastname(lastname_);
        setPatronymic(patronymic_);
        setIin(iin_);
        setBirthDate(birthDate_);
        resetTouchedOnNotNull();
    }
}
