/*
 * This file is generated by jOOQ.
 */
package com.hnu.db.jooq.model.tables.records;


import com.hnu.db.jooq.model.tables.PgpArmorHeaders;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgpArmorHeaderRecord extends TableRecordImpl<PgpArmorHeaderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.pgp_armor_headers.key</code>.
     */
    public void setKey(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pgp_armor_headers.key</code>.
     */
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.pgp_armor_headers.value</code>.
     */
    public void setValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pgp_armor_headers.value</code>.
     */
    public String getValue() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgpArmorHeaderRecord
     */
    public PgpArmorHeaderRecord() {
        super(PgpArmorHeaders.PGP_ARMOR_HEADERS);
    }

    /**
     * Create a detached, initialised PgpArmorHeaderRecord
     */
    public PgpArmorHeaderRecord(String key, String value) {
        super(PgpArmorHeaders.PGP_ARMOR_HEADERS);

        setKey(key);
        setValue(value);
        resetTouchedOnNotNull();
    }
}
