/*
 * This file is generated by jOOQ.
 */
package com.hnu.db.jooq.model.tables.records;


import com.hnu.db.jooq.model.tables.TgUsers;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TgUserRecord extends UpdatableRecordImpl<TgUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tg_users.id_</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tg_users.id_</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.tg_users.removed_</code>.
     */
    public void setRemoved(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tg_users.removed_</code>.
     */
    public Boolean getRemoved() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.tg_users.create_date_</code>.
     */
    public void setCreateDate(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tg_users.create_date_</code>.
     */
    public OffsetDateTime getCreateDate() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.tg_users.modify_date_</code>.
     */
    public void setModifyDate(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tg_users.modify_date_</code>.
     */
    public OffsetDateTime getModifyDate() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.tg_users.phone_</code>.
     */
    public void setPhone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tg_users.phone_</code>.
     */
    public String getPhone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tg_users.telegram_user_id_</code>.
     */
    public void setTelegramUserId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tg_users.telegram_user_id_</code>.
     */
    public Long getTelegramUserId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.tg_users.telegram_chat_id_</code>.
     */
    public void setTelegramChatId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tg_users.telegram_chat_id_</code>.
     */
    public Long getTelegramChatId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.tg_users.telegram_username_</code>.
     */
    public void setTelegramUsername(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tg_users.telegram_username_</code>.
     */
    public String getTelegramUsername() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.tg_users.telegram_language_code_</code>.
     */
    public void setTelegramLanguageCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.tg_users.telegram_language_code_</code>.
     */
    public String getTelegramLanguageCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.tg_users.lastname_</code>.
     */
    public void setLastname(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.tg_users.lastname_</code>.
     */
    public String getLastname() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.tg_users.firstname_</code>.
     */
    public void setFirstname(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.tg_users.firstname_</code>.
     */
    public String getFirstname() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.tg_users.bot_</code>.
     */
    public void setBot(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.tg_users.bot_</code>.
     */
    public String getBot() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.tg_users.enabled_</code>.
     */
    public void setEnabled(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.tg_users.enabled_</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TgUserRecord
     */
    public TgUserRecord() {
        super(TgUsers.TG_USERS);
    }

    /**
     * Create a detached, initialised TgUserRecord
     */
    public TgUserRecord(UUID id_, Boolean removed_, OffsetDateTime createDate_, OffsetDateTime modifyDate_, String phone_, Long telegramUserId_, Long telegramChatId_, String telegramUsername_, String telegramLanguageCode_, String lastname_, String firstname_, String bot_, Boolean enabled_) {
        super(TgUsers.TG_USERS);

        setId(id_);
        setRemoved(removed_);
        setCreateDate(createDate_);
        setModifyDate(modifyDate_);
        setPhone(phone_);
        setTelegramUserId(telegramUserId_);
        setTelegramChatId(telegramChatId_);
        setTelegramUsername(telegramUsername_);
        setTelegramLanguageCode(telegramLanguageCode_);
        setLastname(lastname_);
        setFirstname(firstname_);
        setBot(bot_);
        setEnabled(enabled_);
        resetTouchedOnNotNull();
    }
}
