export * from './auth-resource.service';
import { AuthResourceService } from './auth-resource.service';
export * from './goal-resource.service';
import { GoalResourceService } from './goal-resource.service';
export * from './greeting-resource.service';
import { GreetingResourceService } from './greeting-resource.service';
export * from './telegram-resource.service';
import { TelegramResourceService } from './telegram-resource.service';
export * from './transaction-resource.service';
import { TransactionResourceService } from './transaction-resource.service';
export * from './user-resource.service';
import { UserResourceService } from './user-resource.service';
export const APIS = [AuthResourceService, GoalResourceService, GreetingResourceService, TelegramResourceService, TransactionResourceService, UserResourceService];
