/**
 * FNU API (development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const Authenticator = {
    TELEGRAM: 'TELEGRAM',
    SMS: 'SMS'
} as const;
export type Authenticator = typeof Authenticator[keyof typeof Authenticator];

