/**
 * FNU API (development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthUserModel { 
    id: string;
    phone: string;
    firstname: string;
    lastname?: string;
    patronymic?: string;
}

