quarkus.smallrye-openapi.enable=true

quarkus.http.port=9000

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.validation-query-sql=select 1
quarkus.datasource.jdbc.max-size=20
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/hnu
quarkus.datasource.reactive.url=postgresql://localhost:5432/hnu

quarkus.jooq.dialect=postgresql

quarkus.smallrye-openapi.info-title=FNU API
%dev.quarkus.smallrye-openapi.info-title=FNU API (development)
%test.quarkus.smallrye-openapi.info-title=FNU API (test)
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.security-scheme-name=bearer
quarkus.smallrye-openapi.operation-id-strategy=method
