quarkus.smallrye-openapi.enable=true
quarkus.jackson.serialization-inclusion=non_null

quarkus.http.header."x-app-version".value=0.1.0
quarkus.http.limits.max-body-size=2000M
quarkus.arc.exclude-types=com.fcs.db.jooq.**
quarkus.arc.fail-on-intercepted-private-method=false
quarkus.http.body.uploads-directory=/tmp/fcs-file-uploads
quarkus.log.file.enable=true
%dev.quarkus.log.file.path=build/fcs-app.log
quarkus.log.file.path=/var/log/quarkus/fcs-app.log
quarkus.log.file.level=INFO
quarkus.log.file.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd
quarkus.log.file.rotation.max-backup-index=10
quarkus.log.file.rotation.max-file-size=1000M
quarkus.log.min-level=DEBUG
quarkus.log.category."com.fcs".level=DEBUG
quarkus.default-locale=ru_RU
quarkus.http.body.delete-uploaded-files-on-end=true
quarkus.cache.caffeine.expire-after-write=1h

quarkus.http.port=9000

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.validation-query-sql=select 1
quarkus.datasource.jdbc.max-size=20
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/hnu
quarkus.datasource.reactive.url=postgresql://localhost:5432/hnu

quarkus.jooq.dialect=postgresql

quarkus.smallrye-openapi.info-title=FNU API
%dev.quarkus.smallrye-openapi.info-title=FNU API (development)
%test.quarkus.smallrye-openapi.info-title=FNU API (test)
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.security-scheme-name=bearer
quarkus.smallrye-openapi.operation-id-strategy=method

quarkus.log.level=INFO

auth.available_authenticators=TELEGRAM
tg.token=8050142408:AAGpM7uqflT4EgXtuKZjozt-su0zkBR429Y
tg.botTitle=hnu_dev_bot

quarkus.rest-client.telegram.url=http://localhost:8081
quarkus.rest-client.telegram.scope=jakarta.inject.Singleton

quarkus.http.access-log.enabled=false
quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=50000
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG
