/*
 * This file is generated by jOOQ.
 */
package com.hnu.db.jooq.model.tables;


import com.hnu.db.jooq.model.Keys;
import com.hnu.db.jooq.model.Public;
import com.hnu.db.jooq.model.tables.records.NuGoalRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NuGoals extends TableImpl<NuGoalRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.nu_goals</code>
     */
    public static final NuGoals NU_GOALS = new NuGoals();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NuGoalRecord> getRecordType() {
        return NuGoalRecord.class;
    }

    /**
     * The column <code>public.nu_goals.id_</code>.
     */
    public final TableField<NuGoalRecord, UUID> ID = createField(DSL.name("id_"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v7()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.nu_goals.removed_</code>.
     */
    public final TableField<NuGoalRecord, Boolean> REMOVED = createField(DSL.name("removed_"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.nu_goals.create_date_</code>.
     */
    public final TableField<NuGoalRecord, OffsetDateTime> CREATE_DATE = createField(DSL.name("create_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.nu_goals.modify_date_</code>.
     */
    public final TableField<NuGoalRecord, OffsetDateTime> MODIFY_DATE = createField(DSL.name("modify_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.nu_goals.user_id_</code>.
     */
    public final TableField<NuGoalRecord, UUID> USER_ID = createField(DSL.name("user_id_"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.nu_goals.name_</code>.
     */
    public final TableField<NuGoalRecord, String> NAME = createField(DSL.name("name_"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.nu_goals.duration_month_</code>.
     */
    public final TableField<NuGoalRecord, Integer> DURATION_MONTH = createField(DSL.name("duration_month_"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.nu_goals.monthly_invest_</code>.
     */
    public final TableField<NuGoalRecord, BigDecimal> MONTHLY_INVEST = createField(DSL.name("monthly_invest_"), SQLDataType.NUMERIC(16, 5).nullable(false), this, "");

    /**
     * The column <code>public.nu_goals.target_</code>.
     */
    public final TableField<NuGoalRecord, BigDecimal> TARGET = createField(DSL.name("target_"), SQLDataType.NUMERIC(16, 5).nullable(false), this, "");

    /**
     * The column <code>public.nu_goals.estimated_date_</code>.
     */
    public final TableField<NuGoalRecord, LocalDateTime> ESTIMATED_DATE = createField(DSL.name("estimated_date_"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.nu_goals.balance_</code>.
     */
    public final TableField<NuGoalRecord, BigDecimal> BALANCE = createField(DSL.name("balance_"), SQLDataType.NUMERIC(16, 5).nullable(false), this, "");

    /**
     * The column <code>public.nu_goals.completed_</code>.
     */
    public final TableField<NuGoalRecord, Boolean> COMPLETED = createField(DSL.name("completed_"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    private NuGoals(Name alias, Table<NuGoalRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private NuGoals(Name alias, Table<NuGoalRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.nu_goals</code> table reference
     */
    public NuGoals(String alias) {
        this(DSL.name(alias), NU_GOALS);
    }

    /**
     * Create an aliased <code>public.nu_goals</code> table reference
     */
    public NuGoals(Name alias) {
        this(alias, NU_GOALS);
    }

    /**
     * Create a <code>public.nu_goals</code> table reference
     */
    public NuGoals() {
        this(DSL.name("nu_goals"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<NuGoalRecord> getPrimaryKey() {
        return Keys.NU_GOALS_PKEY;
    }

    @Override
    public NuGoals as(String alias) {
        return new NuGoals(DSL.name(alias), this);
    }

    @Override
    public NuGoals as(Name alias) {
        return new NuGoals(alias, this);
    }

    @Override
    public NuGoals as(Table<?> alias) {
        return new NuGoals(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public NuGoals rename(String name) {
        return new NuGoals(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NuGoals rename(Name name) {
        return new NuGoals(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public NuGoals rename(Table<?> name) {
        return new NuGoals(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuGoals where(Condition condition) {
        return new NuGoals(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuGoals where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuGoals where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuGoals where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuGoals where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuGoals where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuGoals where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuGoals where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuGoals whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuGoals whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
