/*
 * This file is generated by jOOQ.
 */
package com.hnu.db.jooq.model.tables;


import com.hnu.db.jooq.model.Keys;
import com.hnu.db.jooq.model.Public;
import com.hnu.db.jooq.model.tables.records.NuGoalTransactionRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NuGoalTransactions extends TableImpl<NuGoalTransactionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.nu_goal_transactions</code>
     */
    public static final NuGoalTransactions NU_GOAL_TRANSACTIONS = new NuGoalTransactions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NuGoalTransactionRecord> getRecordType() {
        return NuGoalTransactionRecord.class;
    }

    /**
     * The column <code>public.nu_goal_transactions.id_</code>.
     */
    public final TableField<NuGoalTransactionRecord, UUID> ID = createField(DSL.name("id_"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v7()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.nu_goal_transactions.removed_</code>.
     */
    public final TableField<NuGoalTransactionRecord, Boolean> REMOVED = createField(DSL.name("removed_"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.nu_goal_transactions.create_date_</code>.
     */
    public final TableField<NuGoalTransactionRecord, OffsetDateTime> CREATE_DATE = createField(DSL.name("create_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.nu_goal_transactions.modify_date_</code>.
     */
    public final TableField<NuGoalTransactionRecord, OffsetDateTime> MODIFY_DATE = createField(DSL.name("modify_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.nu_goal_transactions.goal_id_</code>.
     */
    public final TableField<NuGoalTransactionRecord, UUID> GOAL_ID = createField(DSL.name("goal_id_"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.nu_goal_transactions.amount_</code>.
     */
    public final TableField<NuGoalTransactionRecord, BigDecimal> AMOUNT = createField(DSL.name("amount_"), SQLDataType.NUMERIC(16, 5).nullable(false), this, "");

    /**
     * The column <code>public.nu_goal_transactions.date_</code>.
     */
    public final TableField<NuGoalTransactionRecord, LocalDateTime> DATE = createField(DSL.name("date_"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private NuGoalTransactions(Name alias, Table<NuGoalTransactionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private NuGoalTransactions(Name alias, Table<NuGoalTransactionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.nu_goal_transactions</code> table
     * reference
     */
    public NuGoalTransactions(String alias) {
        this(DSL.name(alias), NU_GOAL_TRANSACTIONS);
    }

    /**
     * Create an aliased <code>public.nu_goal_transactions</code> table
     * reference
     */
    public NuGoalTransactions(Name alias) {
        this(alias, NU_GOAL_TRANSACTIONS);
    }

    /**
     * Create a <code>public.nu_goal_transactions</code> table reference
     */
    public NuGoalTransactions() {
        this(DSL.name("nu_goal_transactions"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<NuGoalTransactionRecord> getPrimaryKey() {
        return Keys.NU_GOAL_TRANSACTIONS_PKEY;
    }

    @Override
    public NuGoalTransactions as(String alias) {
        return new NuGoalTransactions(DSL.name(alias), this);
    }

    @Override
    public NuGoalTransactions as(Name alias) {
        return new NuGoalTransactions(alias, this);
    }

    @Override
    public NuGoalTransactions as(Table<?> alias) {
        return new NuGoalTransactions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public NuGoalTransactions rename(String name) {
        return new NuGoalTransactions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NuGoalTransactions rename(Name name) {
        return new NuGoalTransactions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public NuGoalTransactions rename(Table<?> name) {
        return new NuGoalTransactions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuGoalTransactions where(Condition condition) {
        return new NuGoalTransactions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuGoalTransactions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuGoalTransactions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuGoalTransactions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuGoalTransactions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuGoalTransactions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuGoalTransactions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuGoalTransactions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuGoalTransactions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuGoalTransactions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
