/*
 * This file is generated by jOOQ.
 */
package com.hnu.db.jooq.model.tables;


import com.hnu.db.jooq.model.Indexes;
import com.hnu.db.jooq.model.Keys;
import com.hnu.db.jooq.model.Public;
import com.hnu.db.jooq.model.tables.records.NuOtpRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NuOtps extends TableImpl<NuOtpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.nu_otps</code>
     */
    public static final NuOtps NU_OTPS = new NuOtps();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NuOtpRecord> getRecordType() {
        return NuOtpRecord.class;
    }

    /**
     * The column <code>public.nu_otps.id_</code>.
     */
    public final TableField<NuOtpRecord, UUID> ID = createField(DSL.name("id_"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v7()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.nu_otps.removed_</code>.
     */
    public final TableField<NuOtpRecord, Boolean> REMOVED = createField(DSL.name("removed_"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.nu_otps.create_date_</code>.
     */
    public final TableField<NuOtpRecord, OffsetDateTime> CREATE_DATE = createField(DSL.name("create_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.nu_otps.modify_date_</code>.
     */
    public final TableField<NuOtpRecord, OffsetDateTime> MODIFY_DATE = createField(DSL.name("modify_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.nu_otps.modify_user_id_</code>.
     */
    public final TableField<NuOtpRecord, UUID> MODIFY_USER_ID = createField(DSL.name("modify_user_id_"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.nu_otps.user_id_</code>.
     */
    public final TableField<NuOtpRecord, UUID> USER_ID = createField(DSL.name("user_id_"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.nu_otps.code_</code>.
     */
    public final TableField<NuOtpRecord, String> CODE = createField(DSL.name("code_"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.nu_otps.success_date_</code>.
     */
    public final TableField<NuOtpRecord, OffsetDateTime> SUCCESS_DATE = createField(DSL.name("success_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.nu_otps.expire_date_</code>.
     */
    public final TableField<NuOtpRecord, OffsetDateTime> EXPIRE_DATE = createField(DSL.name("expire_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.nu_otps.phone_</code>.
     */
    public final TableField<NuOtpRecord, String> PHONE = createField(DSL.name("phone_"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.nu_otps.session_id_</code>.
     */
    public final TableField<NuOtpRecord, String> SESSION_ID = createField(DSL.name("session_id_"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.nu_otps.authenticator_</code>.
     */
    public final TableField<NuOtpRecord, String> AUTHENTICATOR = createField(DSL.name("authenticator_"), SQLDataType.VARCHAR(30), this, "");

    private NuOtps(Name alias, Table<NuOtpRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private NuOtps(Name alias, Table<NuOtpRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.nu_otps</code> table reference
     */
    public NuOtps(String alias) {
        this(DSL.name(alias), NU_OTPS);
    }

    /**
     * Create an aliased <code>public.nu_otps</code> table reference
     */
    public NuOtps(Name alias) {
        this(alias, NU_OTPS);
    }

    /**
     * Create a <code>public.nu_otps</code> table reference
     */
    public NuOtps() {
        this(DSL.name("nu_otps"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.NU_OTPS__PHONE__IDX);
    }

    @Override
    public UniqueKey<NuOtpRecord> getPrimaryKey() {
        return Keys.NU_OTPS_PKEY;
    }

    @Override
    public NuOtps as(String alias) {
        return new NuOtps(DSL.name(alias), this);
    }

    @Override
    public NuOtps as(Name alias) {
        return new NuOtps(alias, this);
    }

    @Override
    public NuOtps as(Table<?> alias) {
        return new NuOtps(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public NuOtps rename(String name) {
        return new NuOtps(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NuOtps rename(Name name) {
        return new NuOtps(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public NuOtps rename(Table<?> name) {
        return new NuOtps(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuOtps where(Condition condition) {
        return new NuOtps(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuOtps where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuOtps where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuOtps where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuOtps where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuOtps where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuOtps where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuOtps where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuOtps whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuOtps whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
