/*
 * This file is generated by jOOQ.
 */
package com.hnu.db.jooq.model.tables;


import com.hnu.db.jooq.model.Keys;
import com.hnu.db.jooq.model.Public;
import com.hnu.db.jooq.model.tables.records.NuOtpRequestRecord;

import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NuOtpRequests extends TableImpl<NuOtpRequestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.nu_otp_requests</code>
     */
    public static final NuOtpRequests NU_OTP_REQUESTS = new NuOtpRequests();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NuOtpRequestRecord> getRecordType() {
        return NuOtpRequestRecord.class;
    }

    /**
     * The column <code>public.nu_otp_requests.id_</code>.
     */
    public final TableField<NuOtpRequestRecord, UUID> ID = createField(DSL.name("id_"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v7()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.nu_otp_requests.removed_</code>.
     */
    public final TableField<NuOtpRequestRecord, Boolean> REMOVED = createField(DSL.name("removed_"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.nu_otp_requests.create_date_</code>.
     */
    public final TableField<NuOtpRequestRecord, OffsetDateTime> CREATE_DATE = createField(DSL.name("create_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.nu_otp_requests.modify_date_</code>.
     */
    public final TableField<NuOtpRequestRecord, OffsetDateTime> MODIFY_DATE = createField(DSL.name("modify_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.nu_otp_requests.modify_user_id_</code>.
     */
    public final TableField<NuOtpRequestRecord, UUID> MODIFY_USER_ID = createField(DSL.name("modify_user_id_"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.nu_otp_requests.code_</code>.
     */
    public final TableField<NuOtpRequestRecord, String> CODE = createField(DSL.name("code_"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.nu_otp_requests.otp_id_</code>.
     */
    public final TableField<NuOtpRequestRecord, UUID> OTP_ID = createField(DSL.name("otp_id_"), SQLDataType.UUID, this, "");

    private NuOtpRequests(Name alias, Table<NuOtpRequestRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private NuOtpRequests(Name alias, Table<NuOtpRequestRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.nu_otp_requests</code> table reference
     */
    public NuOtpRequests(String alias) {
        this(DSL.name(alias), NU_OTP_REQUESTS);
    }

    /**
     * Create an aliased <code>public.nu_otp_requests</code> table reference
     */
    public NuOtpRequests(Name alias) {
        this(alias, NU_OTP_REQUESTS);
    }

    /**
     * Create a <code>public.nu_otp_requests</code> table reference
     */
    public NuOtpRequests() {
        this(DSL.name("nu_otp_requests"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<NuOtpRequestRecord> getPrimaryKey() {
        return Keys.NU_OTP_REQUESTS_PKEY;
    }

    @Override
    public NuOtpRequests as(String alias) {
        return new NuOtpRequests(DSL.name(alias), this);
    }

    @Override
    public NuOtpRequests as(Name alias) {
        return new NuOtpRequests(alias, this);
    }

    @Override
    public NuOtpRequests as(Table<?> alias) {
        return new NuOtpRequests(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public NuOtpRequests rename(String name) {
        return new NuOtpRequests(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NuOtpRequests rename(Name name) {
        return new NuOtpRequests(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public NuOtpRequests rename(Table<?> name) {
        return new NuOtpRequests(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuOtpRequests where(Condition condition) {
        return new NuOtpRequests(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuOtpRequests where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuOtpRequests where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuOtpRequests where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuOtpRequests where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuOtpRequests where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuOtpRequests where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuOtpRequests where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuOtpRequests whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuOtpRequests whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
