/*
 * This file is generated by jOOQ.
 */
package com.hnu.db.jooq.model.tables;


import com.hnu.db.jooq.model.Public;
import com.hnu.db.jooq.model.tables.records.NuSessionRecord;

import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NuSessions extends TableImpl<NuSessionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.nu_sessions</code>
     */
    public static final NuSessions NU_SESSIONS = new NuSessions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NuSessionRecord> getRecordType() {
        return NuSessionRecord.class;
    }

    /**
     * The column <code>public.nu_sessions.session_id_</code>.
     */
    public final TableField<NuSessionRecord, String> SESSION_ID = createField(DSL.name("session_id_"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.nu_sessions.removed_</code>.
     */
    public final TableField<NuSessionRecord, Boolean> REMOVED = createField(DSL.name("removed_"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.nu_sessions.create_date_</code>.
     */
    public final TableField<NuSessionRecord, OffsetDateTime> CREATE_DATE = createField(DSL.name("create_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.nu_sessions.modify_date_</code>.
     */
    public final TableField<NuSessionRecord, OffsetDateTime> MODIFY_DATE = createField(DSL.name("modify_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.nu_sessions.user_id_</code>.
     */
    public final TableField<NuSessionRecord, UUID> USER_ID = createField(DSL.name("user_id_"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.nu_sessions.phone_</code>.
     */
    public final TableField<NuSessionRecord, String> PHONE = createField(DSL.name("phone_"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.nu_sessions.data_</code>.
     */
    public final TableField<NuSessionRecord, JSONB> DATA = createField(DSL.name("data_"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.nu_sessions.expire_date_</code>.
     */
    public final TableField<NuSessionRecord, OffsetDateTime> EXPIRE_DATE = createField(DSL.name("expire_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.nu_sessions.device_id_</code>.
     */
    public final TableField<NuSessionRecord, UUID> DEVICE_ID = createField(DSL.name("device_id_"), SQLDataType.UUID, this, "");

    private NuSessions(Name alias, Table<NuSessionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private NuSessions(Name alias, Table<NuSessionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.nu_sessions</code> table reference
     */
    public NuSessions(String alias) {
        this(DSL.name(alias), NU_SESSIONS);
    }

    /**
     * Create an aliased <code>public.nu_sessions</code> table reference
     */
    public NuSessions(Name alias) {
        this(alias, NU_SESSIONS);
    }

    /**
     * Create a <code>public.nu_sessions</code> table reference
     */
    public NuSessions() {
        this(DSL.name("nu_sessions"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public NuSessions as(String alias) {
        return new NuSessions(DSL.name(alias), this);
    }

    @Override
    public NuSessions as(Name alias) {
        return new NuSessions(alias, this);
    }

    @Override
    public NuSessions as(Table<?> alias) {
        return new NuSessions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public NuSessions rename(String name) {
        return new NuSessions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NuSessions rename(Name name) {
        return new NuSessions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public NuSessions rename(Table<?> name) {
        return new NuSessions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuSessions where(Condition condition) {
        return new NuSessions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuSessions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuSessions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuSessions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuSessions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuSessions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuSessions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuSessions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuSessions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuSessions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
