/*
 * This file is generated by jOOQ.
 */
package com.hnu.db.jooq.model.tables;


import com.hnu.db.jooq.model.Keys;
import com.hnu.db.jooq.model.Public;
import com.hnu.db.jooq.model.tables.records.NuTransactionRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NuTransactions extends TableImpl<NuTransactionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.nu_transactions</code>
     */
    public static final NuTransactions NU_TRANSACTIONS = new NuTransactions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NuTransactionRecord> getRecordType() {
        return NuTransactionRecord.class;
    }

    /**
     * The column <code>public.nu_transactions.id_</code>.
     */
    public final TableField<NuTransactionRecord, UUID> ID = createField(DSL.name("id_"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v7()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.nu_transactions.removed_</code>.
     */
    public final TableField<NuTransactionRecord, Boolean> REMOVED = createField(DSL.name("removed_"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.nu_transactions.create_date_</code>.
     */
    public final TableField<NuTransactionRecord, OffsetDateTime> CREATE_DATE = createField(DSL.name("create_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.nu_transactions.modify_date_</code>.
     */
    public final TableField<NuTransactionRecord, OffsetDateTime> MODIFY_DATE = createField(DSL.name("modify_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.nu_transactions.user_id</code>.
     */
    public final TableField<NuTransactionRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.nu_transactions.amount_</code>.
     */
    public final TableField<NuTransactionRecord, BigDecimal> AMOUNT = createField(DSL.name("amount_"), SQLDataType.NUMERIC(16, 5).nullable(false), this, "");

    /**
     * The column <code>public.nu_transactions.category_type_</code>.
     */
    public final TableField<NuTransactionRecord, String> CATEGORY_TYPE = createField(DSL.name("category_type_"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.nu_transactions.date_</code>.
     */
    public final TableField<NuTransactionRecord, LocalDateTime> DATE = createField(DSL.name("date_"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private NuTransactions(Name alias, Table<NuTransactionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private NuTransactions(Name alias, Table<NuTransactionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.nu_transactions</code> table reference
     */
    public NuTransactions(String alias) {
        this(DSL.name(alias), NU_TRANSACTIONS);
    }

    /**
     * Create an aliased <code>public.nu_transactions</code> table reference
     */
    public NuTransactions(Name alias) {
        this(alias, NU_TRANSACTIONS);
    }

    /**
     * Create a <code>public.nu_transactions</code> table reference
     */
    public NuTransactions() {
        this(DSL.name("nu_transactions"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<NuTransactionRecord> getPrimaryKey() {
        return Keys.NU_TRANSACTIONS_PKEY;
    }

    @Override
    public NuTransactions as(String alias) {
        return new NuTransactions(DSL.name(alias), this);
    }

    @Override
    public NuTransactions as(Name alias) {
        return new NuTransactions(alias, this);
    }

    @Override
    public NuTransactions as(Table<?> alias) {
        return new NuTransactions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public NuTransactions rename(String name) {
        return new NuTransactions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NuTransactions rename(Name name) {
        return new NuTransactions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public NuTransactions rename(Table<?> name) {
        return new NuTransactions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuTransactions where(Condition condition) {
        return new NuTransactions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuTransactions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuTransactions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuTransactions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuTransactions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuTransactions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuTransactions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuTransactions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuTransactions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuTransactions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
