/*
 * This file is generated by jOOQ.
 */
package com.hnu.db.jooq.model.tables;


import com.hnu.db.jooq.model.Keys;
import com.hnu.db.jooq.model.Public;
import com.hnu.db.jooq.model.tables.records.NuUserRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NuUsers extends TableImpl<NuUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.nu_users</code>
     */
    public static final NuUsers NU_USERS = new NuUsers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NuUserRecord> getRecordType() {
        return NuUserRecord.class;
    }

    /**
     * The column <code>public.nu_users.id_</code>.
     */
    public final TableField<NuUserRecord, UUID> ID = createField(DSL.name("id_"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v7()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.nu_users.removed_</code>.
     */
    public final TableField<NuUserRecord, Boolean> REMOVED = createField(DSL.name("removed_"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.nu_users.create_date_</code>.
     */
    public final TableField<NuUserRecord, OffsetDateTime> CREATE_DATE = createField(DSL.name("create_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.nu_users.modify_date_</code>.
     */
    public final TableField<NuUserRecord, OffsetDateTime> MODIFY_DATE = createField(DSL.name("modify_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.nu_users.modify_user_id_</code>.
     */
    public final TableField<NuUserRecord, UUID> MODIFY_USER_ID = createField(DSL.name("modify_user_id_"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.nu_users.enabled_</code>.
     */
    public final TableField<NuUserRecord, Boolean> ENABLED = createField(DSL.name("enabled_"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.nu_users.phone_</code>.
     */
    public final TableField<NuUserRecord, String> PHONE = createField(DSL.name("phone_"), SQLDataType.VARCHAR(15).nullable(false), this, "");

    /**
     * The column <code>public.nu_users.firstname_</code>.
     */
    public final TableField<NuUserRecord, String> FIRSTNAME = createField(DSL.name("firstname_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.nu_users.lastname_</code>.
     */
    public final TableField<NuUserRecord, String> LASTNAME = createField(DSL.name("lastname_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.nu_users.patronymic_</code>.
     */
    public final TableField<NuUserRecord, String> PATRONYMIC = createField(DSL.name("patronymic_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.nu_users.iin_</code>.
     */
    public final TableField<NuUserRecord, String> IIN = createField(DSL.name("iin_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.nu_users.birth_date_</code>.
     */
    public final TableField<NuUserRecord, OffsetDateTime> BIRTH_DATE = createField(DSL.name("birth_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private NuUsers(Name alias, Table<NuUserRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private NuUsers(Name alias, Table<NuUserRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.nu_users</code> table reference
     */
    public NuUsers(String alias) {
        this(DSL.name(alias), NU_USERS);
    }

    /**
     * Create an aliased <code>public.nu_users</code> table reference
     */
    public NuUsers(Name alias) {
        this(alias, NU_USERS);
    }

    /**
     * Create a <code>public.nu_users</code> table reference
     */
    public NuUsers() {
        this(DSL.name("nu_users"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<NuUserRecord> getPrimaryKey() {
        return Keys.NU_USERS_PKEY;
    }

    @Override
    public List<UniqueKey<NuUserRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.NU_USERS_PHONE__KEY);
    }

    @Override
    public NuUsers as(String alias) {
        return new NuUsers(DSL.name(alias), this);
    }

    @Override
    public NuUsers as(Name alias) {
        return new NuUsers(alias, this);
    }

    @Override
    public NuUsers as(Table<?> alias) {
        return new NuUsers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public NuUsers rename(String name) {
        return new NuUsers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NuUsers rename(Name name) {
        return new NuUsers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public NuUsers rename(Table<?> name) {
        return new NuUsers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuUsers where(Condition condition) {
        return new NuUsers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuUsers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuUsers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuUsers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuUsers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuUsers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuUsers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NuUsers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuUsers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NuUsers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
