/*
 * This file is generated by jOOQ.
 */
package com.hnu.db.jooq.model.tables;


import com.hnu.db.jooq.model.Indexes;
import com.hnu.db.jooq.model.Keys;
import com.hnu.db.jooq.model.Public;
import com.hnu.db.jooq.model.tables.records.TgUserRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TgUsers extends TableImpl<TgUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.tg_users</code>
     */
    public static final TgUsers TG_USERS = new TgUsers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TgUserRecord> getRecordType() {
        return TgUserRecord.class;
    }

    /**
     * The column <code>public.tg_users.id_</code>.
     */
    public final TableField<TgUserRecord, UUID> ID = createField(DSL.name("id_"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v7()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.tg_users.removed_</code>.
     */
    public final TableField<TgUserRecord, Boolean> REMOVED = createField(DSL.name("removed_"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.tg_users.create_date_</code>.
     */
    public final TableField<TgUserRecord, OffsetDateTime> CREATE_DATE = createField(DSL.name("create_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.tg_users.modify_date_</code>.
     */
    public final TableField<TgUserRecord, OffsetDateTime> MODIFY_DATE = createField(DSL.name("modify_date_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.tg_users.phone_</code>.
     */
    public final TableField<TgUserRecord, String> PHONE = createField(DSL.name("phone_"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>public.tg_users.telegram_user_id_</code>.
     */
    public final TableField<TgUserRecord, Long> TELEGRAM_USER_ID = createField(DSL.name("telegram_user_id_"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.tg_users.telegram_chat_id_</code>.
     */
    public final TableField<TgUserRecord, Long> TELEGRAM_CHAT_ID = createField(DSL.name("telegram_chat_id_"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.tg_users.telegram_username_</code>.
     */
    public final TableField<TgUserRecord, String> TELEGRAM_USERNAME = createField(DSL.name("telegram_username_"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.tg_users.telegram_language_code_</code>.
     */
    public final TableField<TgUserRecord, String> TELEGRAM_LANGUAGE_CODE = createField(DSL.name("telegram_language_code_"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.tg_users.lastname_</code>.
     */
    public final TableField<TgUserRecord, String> LASTNAME = createField(DSL.name("lastname_"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.tg_users.firstname_</code>.
     */
    public final TableField<TgUserRecord, String> FIRSTNAME = createField(DSL.name("firstname_"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.tg_users.bot_</code>.
     */
    public final TableField<TgUserRecord, String> BOT = createField(DSL.name("bot_"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.tg_users.enabled_</code>.
     */
    public final TableField<TgUserRecord, Boolean> ENABLED = createField(DSL.name("enabled_"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    private TgUsers(Name alias, Table<TgUserRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TgUsers(Name alias, Table<TgUserRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.tg_users</code> table reference
     */
    public TgUsers(String alias) {
        this(DSL.name(alias), TG_USERS);
    }

    /**
     * Create an aliased <code>public.tg_users</code> table reference
     */
    public TgUsers(Name alias) {
        this(alias, TG_USERS);
    }

    /**
     * Create a <code>public.tg_users</code> table reference
     */
    public TgUsers() {
        this(DSL.name("tg_users"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.TG_USERS__CHAT_USER_BOT__UIDX);
    }

    @Override
    public UniqueKey<TgUserRecord> getPrimaryKey() {
        return Keys.TG_USERS_PKEY;
    }

    @Override
    public List<UniqueKey<TgUserRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.TG_USERS_PHONE__KEY, Keys.TG_USERS_TELEGRAM_USER_ID__KEY);
    }

    @Override
    public TgUsers as(String alias) {
        return new TgUsers(DSL.name(alias), this);
    }

    @Override
    public TgUsers as(Name alias) {
        return new TgUsers(alias, this);
    }

    @Override
    public TgUsers as(Table<?> alias) {
        return new TgUsers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TgUsers rename(String name) {
        return new TgUsers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TgUsers rename(Name name) {
        return new TgUsers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TgUsers rename(Table<?> name) {
        return new TgUsers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TgUsers where(Condition condition) {
        return new TgUsers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TgUsers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TgUsers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TgUsers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TgUsers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TgUsers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TgUsers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TgUsers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TgUsers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TgUsers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
