#if you need to have java.util.Date, java.sql.* in generated classes instead of cool new java.time.* then set value to 'false'

nu.enabled=false
nu.destination=dao/nu/src/main/java
nu.package=com.hnu.db.jooq.model
nu.db.user=postgres
nu.db.password=postgres
nu.db.name=nu
nu.db.host=localhost
nu.db.port=5432
nu.java8date=true
nu.routine=true
